// <auto-generated />
using System;
using BusinessPlanSimulator.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessPlanSimulator.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BusinessPlanSimulator.Api.Models.Entities.AssetInvestment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessPlanId")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("UnitValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsefulLifeYears")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusinessPlanId");

                    b.ToTable("AssetInvestments");
                });

            modelBuilder.Entity("BusinessPlanSimulator.Api.Models.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("BusinessPlanSimulator.Api.Models.Entities.BusinessPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorUserId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("CompanyType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("LifespanYears")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MacroplanId")
                        .HasColumnType("int");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("MacroplanId");

                    b.ToTable("BusinessPlans");
                });

            modelBuilder.Entity("BusinessPlanSimulator.Api.Models.Entities.BusinessPlanSetting", b =>
                {
                    b.Property<int>("BusinessPlanId")
                        .HasColumnType("int");

                    b.Property<decimal>("ChristmasBonusRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("CollectionDays")
                        .HasColumnType("int");

                    b.Property<int>("DebtTermYears")
                        .HasColumnType("int");

                    b.Property<decimal>("EmployerTaxRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("InatecTaxRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("MarketArea")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("MonthlyPayrollExpense")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OtherProvisionsRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("SalesCommissionRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("SeveranceRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("StartYear")
                        .HasColumnType("int");

                    b.Property<int>("SupplierPaymentDays")
                        .HasColumnType("int");

                    b.Property<decimal>("VacationRate")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("BusinessPlanId");

                    b.ToTable("BusinessPlanSettings");
                });

            modelBuilder.Entity("BusinessPlanSimulator.Api.Models.Entities.MacroeconomicParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessPlanId")
                        .HasColumnType("int");

                    b.Property<decimal>("GdpGrowthRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("IncomeTaxRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("InflationRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ProjectRiskPremium")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ReferenceInterestRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("RiskFreeRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("TMAR")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("WACC")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("YearIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusinessPlanId");

                    b.ToTable("MacroeconomicParameters");
                });

            modelBuilder.Entity("BusinessPlanSimulator.Api.Models.Entities.Macroplan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("ValidityEndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ValidityStartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Macroplans");
                });

            modelBuilder.Entity("BusinessPlanSimulator.Api.Models.Entities.OperationalExpense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessPlanId")
                        .HasColumnType("int");

                    b.Property<string>("Concept")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("Year1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Year2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Year3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Year4")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Year5")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessPlanId");

                    b.ToTable("OperationalExpenses");
                });

            modelBuilder.Entity("BusinessPlanSimulator.Api.Models.Entities.PlanReviewNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessPlanId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ReviewerUserId")
                        .HasColumnType("int");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessPlanId");

                    b.HasIndex("ReviewerUserId");

                    b.ToTable("PlanReviewNotes");
                });

            modelBuilder.Entity("BusinessPlanSimulator.Api.Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AnnualGrowthRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("BaseYearDemand")
                        .HasColumnType("int");

                    b.Property<int>("BatchSize")
                        .HasColumnType("int");

                    b.Property<int>("BusinessPlanId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FinishedGoodsInventoryDays")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("TargetPriceCostRatio")
                        .HasColumnType("decimal(8,4)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessPlanId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BusinessPlanSimulator.Api.Models.Entities.ProductBOM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantityPerBatch")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("RawMaterialId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("RawMaterialId");

                    b.ToTable("ProductBOMs");
                });

            modelBuilder.Entity("BusinessPlanSimulator.Api.Models.Entities.ProductOverhead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Concept")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantityPerBatch")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductOverheads");
                });

            modelBuilder.Entity("BusinessPlanSimulator.Api.Models.Entities.RawMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessPlanId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<int>("RawMaterialInventoryDays")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessPlanId");

                    b.ToTable("RawMaterials");
                });

            modelBuilder.Entity("BusinessPlanSimulator.Api.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BusinessPlanSimulator.Api.Models.Entities.AssetInvestment", b =>
                {
                    b.HasOne("BusinessPlanSimulator.Api.Models.Entities.BusinessPlan", "BusinessPlan")
                        .WithMany()
                        .HasForeignKey("BusinessPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessPlan");
                });

            modelBuilder.Entity("BusinessPlanSimulator.Api.Models.Entities.AuditLog", b =>
                {
                    b.HasOne("BusinessPlanSimulator.Api.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessPlanSimulator.Api.Models.Entities.BusinessPlan", b =>
                {
                    b.HasOne("BusinessPlanSimulator.Api.Models.Entities.User", "AuthorUser")
                        .WithMany("BusinessPlans")
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BusinessPlanSimulator.Api.Models.Entities.Macroplan", "Macroplan")
                        .WithMany("BusinessPlans")
                        .HasForeignKey("MacroplanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuthorUser");

                    b.Navigation("Macroplan");
                });

            modelBuilder.Entity("BusinessPlanSimulator.Api.Models.Entities.BusinessPlanSetting", b =>
                {
                    b.HasOne("BusinessPlanSimulator.Api.Models.Entities.BusinessPlan", "BusinessPlan")
                        .WithOne()
                        .HasForeignKey("BusinessPlanSimulator.Api.Models.Entities.BusinessPlanSetting", "BusinessPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessPlan");
                });

            modelBuilder.Entity("BusinessPlanSimulator.Api.Models.Entities.MacroeconomicParameter", b =>
                {
                    b.HasOne("BusinessPlanSimulator.Api.Models.Entities.BusinessPlan", "BusinessPlan")
                        .WithMany()
                        .HasForeignKey("BusinessPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessPlan");
                });

            modelBuilder.Entity("BusinessPlanSimulator.Api.Models.Entities.Macroplan", b =>
                {
                    b.HasOne("BusinessPlanSimulator.Api.Models.Entities.User", "CreatedByUser")
                        .WithMany("Macroplans")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("BusinessPlanSimulator.Api.Models.Entities.OperationalExpense", b =>
                {
                    b.HasOne("BusinessPlanSimulator.Api.Models.Entities.BusinessPlan", "BusinessPlan")
                        .WithMany()
                        .HasForeignKey("BusinessPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessPlan");
                });

            modelBuilder.Entity("BusinessPlanSimulator.Api.Models.Entities.PlanReviewNote", b =>
                {
                    b.HasOne("BusinessPlanSimulator.Api.Models.Entities.BusinessPlan", "BusinessPlan")
                        .WithMany()
                        .HasForeignKey("BusinessPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessPlanSimulator.Api.Models.Entities.User", "ReviewerUser")
                        .WithMany()
                        .HasForeignKey("ReviewerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusinessPlan");

                    b.Navigation("ReviewerUser");
                });

            modelBuilder.Entity("BusinessPlanSimulator.Api.Models.Entities.Product", b =>
                {
                    b.HasOne("BusinessPlanSimulator.Api.Models.Entities.BusinessPlan", "BusinessPlan")
                        .WithMany()
                        .HasForeignKey("BusinessPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessPlan");
                });

            modelBuilder.Entity("BusinessPlanSimulator.Api.Models.Entities.ProductBOM", b =>
                {
                    b.HasOne("BusinessPlanSimulator.Api.Models.Entities.Product", "Product")
                        .WithMany("BillOfMaterials")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessPlanSimulator.Api.Models.Entities.RawMaterial", "RawMaterial")
                        .WithMany()
                        .HasForeignKey("RawMaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("RawMaterial");
                });

            modelBuilder.Entity("BusinessPlanSimulator.Api.Models.Entities.ProductOverhead", b =>
                {
                    b.HasOne("BusinessPlanSimulator.Api.Models.Entities.Product", "Product")
                        .WithMany("Overheads")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BusinessPlanSimulator.Api.Models.Entities.RawMaterial", b =>
                {
                    b.HasOne("BusinessPlanSimulator.Api.Models.Entities.BusinessPlan", "BusinessPlan")
                        .WithMany()
                        .HasForeignKey("BusinessPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BusinessPlan");
                });

            modelBuilder.Entity("BusinessPlanSimulator.Api.Models.Entities.Macroplan", b =>
                {
                    b.Navigation("BusinessPlans");
                });

            modelBuilder.Entity("BusinessPlanSimulator.Api.Models.Entities.Product", b =>
                {
                    b.Navigation("BillOfMaterials");

                    b.Navigation("Overheads");
                });

            modelBuilder.Entity("BusinessPlanSimulator.Api.Models.Entities.User", b =>
                {
                    b.Navigation("BusinessPlans");

                    b.Navigation("Macroplans");
                });
#pragma warning restore 612, 618
        }
    }
}
